# Generated by Django 5.1.7 on 2025-03-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utilisateur', models.CharField(max_length=100)),
                ('commentaire', models.TextField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('sentiment', models.CharField(choices=[('Positif', 'Positif'), ('Neutre', 'Neutre'), ('Négatif', 'Négatif')], default='Neutre', max_length=10)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='shop.produit')),
            ],
        ),
    ]
